language: python

notifications:
  email: false

python:
  - 3.7

before_install:
  - pip3 install pytest
  - pip3 install codecov

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest
  - coverage run ./tests/test_compute_gradients.py
  - coverage run ./tests/test_feedforward.py
  - coverage combine

after_success:
  - codecov